### ISSUE TITLE
마이페이지 꿀단지 버튼 opacity

### ISSUE THREAD

**Issue by Shugaroon** [Smurfs-village/Buddy-Bee#506]
# 🍯 마이페이지 꿀단지 버튼 opacity

## ✅ 체크리스트

- [x] <작성한 글 / 참여 중 프로젝트> -> 종료 후에도 취소 버튼 opacity 값 유지

- [x] <나의 꿀단지> -> 종료 후에도 꿀단지 버튼은 opacity 값 유지

수정 완료 , 확인요망

-------------------------
📝[노션링크](https://www.notion.so/a2da5a004b064efd920b4af6689d8109?v=1a40cc7b141a42bf9a65ee35bdf16099) - 노션 기능 명세서 참고

**Comment by yoon-arc** [comment]
1. 종료 후 overlay가 꿀단지 버튼 포함해서 덮어지므로 
.Bookmarks_honeyPot_img 에 position absolute 추가해서 top,right 각각 3px 준 뒤 z-index값 주면 될 것 같음

2. {isFinished ? "Bookmarks_finishedProject_container" : ""}`}를 컨테이너 전체에 주지 말고 .Bookmarks_main_right_container_box 따로 .Bookmarks_main_right_container_box_text_wrapper 스타일 따로 적용할 필요 있음

 -> 먼저 .Bookmarks_main_right_container_box_img_wrapper에서 border-bottom을 없애고 .Bookmarks_main_right_container_box_text_wrapper에 border-top을 추가해서 opacity로 조절할 수 있게 변경(img_wrapper에서opacity 넣을 경우 꿀단지 버튼도 영향 받기 때문)
 ->  Bookmarks_finishedProject_container에서 opacity : 0.6->border: 2px solid rgb(119, 119, 119); 으로 변경 후  .Bookmarks_main_right_container_box 에만 적용 되게 변경 
 -> .Bookmarks_main_right_container_box_text_wrapper쪽에 {isFinished ? Bookmarks_finishedProject_text_wrapper ~ 추가 -> css에서 .Bookmarks_finishedProject_text_wrapper -> opacity: 0.6; 넣기
