### ISSUE TITLE
CICD 파이프라인 빌드가 터지지 않도록 개선이 필요해요.

### ISSUE THREAD

**Issue by GeunSam2** [Smurfs-village/Buddy-Bee#547]
제가 제안드린 방식은
git pull
docker build
docker compose 실행까지 모든 과정을 remote 서버에서 실행을 하는 구조인데, 
서버가 docker build까지 수행할 수 있을만큼 리소스가 넉넉하지 않아 빌드를 하다가 터진 것으로 보여요.
(특히 서버가 떠있는데 빌드까지 하면 이렇게 될 것으로 예상되요.)

이를 방지하기 위해서,
git pull -> docker build 단계를 github action이 제공하는 무료 서버에서 진행하고, 
서버에서 이어받기 위해 docker image를 docker hub를 통해 공유하는 과정이 필요합니다.

서버에서는
docker pull, docker restart를 통해 문제를 해결할 수 있어요.

---

해결하기 위한 PR을 선물로 던져드릴게요.

**Comment by yoon-arc** [comment]
헉.. 너무 감사합니다 멘토님!!!
